-- put under user.* to avoid naming conflicts
require "user.plugins"
require "user.keymaps"
require "user.nvim-tree"
require "user.options"
require "user.lsp"
require "user.lualine"
require "user.cmp"
require "user.autopairs"
require "user.treesitter"
